epiquote_homepage:
    pattern:  /
    defaults: { _controller: EpiquoteQuotesBundle:Default:index }
    
EpiquotePagesBundle:
    resource: "@EpiquotePagesBundle/Resources/config/routing.yml"
    prefix:   /pages/

EpiquoteSecurityBundle:
    resource: "@EpiquoteSecurityBundle/Resources/config/routing.yml"
    prefix:   /

EpiquoteQuotesBundle:
    resource: "@EpiquoteQuotesBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
