security:
    encoders:
        Epiquote\SecurityBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Epiquote\SecurityBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login: ~
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: '^/quotes/[^/]+/edit', roles: ROLE_ADMIN }
        - { path: '^/quotes/[^/]+/delete', roles: ROLE_ADMIN }
        - { path: '^/user/.*', roles: ROLE_SUPER_ADMIN }
