quote_show:
    pattern:  /{id}/show
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:show" }

quote_new:
    pattern:  /new
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:new" }

quote_create:
    pattern:  /create
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:create" }
    requirements: { _method: post }

quote_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:edit" }
    requirements:
      id: \d+

quote_update:
    pattern:  /{id}/update
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:update" }
    requirements: { _method: post, id: \d+ }

quote_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:delete" }
    requirements: { _method: post, id: \d+ }
    
quote_search:
    pattern: /search
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:search" }
    
quote_upvote:
    pattern: /{id}/upvote
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:vote", delta: 1 }
    requirements:
      id: \d+
    
quote_downvote:
    pattern: /{id}/downvote
    defaults: { _controller: "EpiquoteQuotesBundle:Quote:vote", delta: -1 }
    requirements:
      id: \d+
      
quote_list:
    pattern:  /{ordering}/{page}
    defaults:
      _controller: "EpiquoteQuotesBundle:Quote:list"
      ordering: lastest
      page: 1
    requirements:
      page: \d+

