search_results:
    pattern: search.{_format}/{page}
    defaults: { _controller: "EpiquoteQuotesBundle:Search:results", page: 1, _format: html }
    requirements:
      _format:  html|json
      page:     \d+
      
autocomplete_author:
    pattern: search/author
    defaults: { _controller: "EpiquoteQuotesBundle:Search:autocompleteAuthor", _format: json }