parameters:
#    epiquote_pages.example.class: Epiquote\PagesBundle\Example

services:
#    epiquote_pages.example:
#        class: %epiquote_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
