parameters:
#    epiquote_quotes.example.class: Epiquote\QuotesBundle\Example

services:
#    epiquote_quotes.example:
#        class: %epiquote_quotes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
