parameters:
#    epiquote_security.example.class: Epiquote\SecurityBundle\Example

services:
#    epiquote_security.example:
#        class: %epiquote_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
